#include<iostream>
using namespace std;

int main()
{
	//This is a wrong setence that awaiting correcting...
	//take a huge change...
	cout<<"Hello World!"<<endl;
	//a little more change...
	//pretend debugging...
	return 0;
}
